### ISSUE TITLE
nvim dap rejects breakpoints and hence nvim-dap-ui closes instantly

### ISSUE THREAD

**Issue by adityababerwal** [dreamsofcode-io/neovim-cpp#2]

**Comment by adityababerwal** [comment]
I compile the file with `g++ -g -O3 main.cpp -o main` and have breakpoints set as:
![image](https://github.com/dreamsofcode-io/neovim-cpp/assets/106467696/07a817f1-9d5c-414c-af7c-ca1e04845b51)
After that I run `:DapContinue` with `<leader>dr`, the nvim-dap-ui opens and closes in a flash.
I have to run `:lua require('dapui').toggle()` to see what happened:
![image](https://github.com/dreamsofcode-io/neovim-cpp/assets/106467696/d8f09927-dcc4-4fff-92a3-729fb25668c8)
The debugger does not stop at the breakpoints. Also the 'R' at place of breakpoints, I read that it means the breakpoint was rejected by debugger.
There are no steps to reproduce this error, I just git cloned this repo in my nvim config. I have installed clangd, clang-format and codelldb with mason.

**Comment by gokulp01** [comment]
Hi, I was wondering if you sorted this issue out. Ended up with the same issue

**Comment by adityababerwal** [comment]
Hi,
I just gave up on getting it to work. Currently working without a debugger.

**Comment by gokulp01** [comment]
So, from what I understood, if your code compiles without any errors, you can use the debugger without any problems.

**Comment by adityababerwal** [comment]
Let's move to discord. My username is 'master.of.fool.hardy.plans', display
name 'jolly roger'.

**Comment by adityababerwal** [comment]
It does compile without any errors.
Here is a video of my issue:

https://github.com/dreamsofcode-io/neovim-cpp/assets/106467696/f0d523cd-0007-442b-9e72-9da064770209
