### ISSUE TITLE
Issue while debugging cpp code

### ISSUE THREAD

**Issue by gokulp01** [dreamsofcode-io/neovim-cpp#3]
Hi, 

Thanks for this awesome config, I am facing this issue while debugging any cpp file. Attached is a screenshot. 

<img width="841" alt="image" src="https://github.com/dreamsofcode-io/neovim-cpp/assets/43350089/cd5367ac-f19b-4fe5-a500-d721778661a9">

Any help will be much appreciated. 

Thanks!

**Comment by Ethanscharlie** [comment]
How did you end up fixing this?

**Comment by gokulp01** [comment]
It's been a while but I think all I had to do was MasonInstall

**Comment by gregszalay** [comment]
I had the same error. In my case I just forgot to add the event = "VeryLazy" line here:
```
  {
    "jay-babu/mason-nvim-dap.nvim",
    event = "VeryLazy",
    dependencies = {
      "williamboman/mason.nvim",
      "mfussenegger/nvim-dap",
    },
    opts = {
      handlers = {},
    },
  },
```
